version: '3.5'
services:
  gitlab:
    image: $GITLAB_VERSION
    hostname: $GITLAB_HOST
    restart: unless-stopped
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        external_url "https://$GITLAB_URL:443"
    ports:
      - "$GITLAB_HTTPS:443"
      - "$GITLAB_HTTP:80"
      - "$GITLAB_SSH:22"
    volumes:
      - $GITLAB_HOME/etc/gitlab:/etc/gitlab
      - $GITLAB_HOME/var/opt/gitlab:/var/opt/gitlab
      - $GITLAB_HOME/var/log/gitlab:/var/log/gitlab
    container_name: $GITLAB_CONTAINER_NAME
    networks:
      - gitlab_net

  gitlab-runner:
    image: $GITLAB_RUNNER
    restart: unless-stopped
    depends_on:
      - gitlab
    volumes:
      - $GITLAB_HOME/etc/gitlab-runner:/etc/gitlab-runner
      - $GITLAB_HOME/var/run/docker.sock:/var/run/docker.sock
    container_name: $GITLAB_RUNNER_NAME
    networks:
      - gitlab_net

networks:
  gitlab_net:
    external:
      name: $GITLAB_NETWORK